name: Docker Image CI

on:
  push:
    branches:
      - main
      - not-main-(dev)
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set Docker tag based on branch
      id: vars
      run: |
        if [[ "${GITHUB_REF##*/}" == "main" ]]; then
          echo "tag=latest" >> $GITHUB_OUTPUT
        else
          echo "tag=dev" >> $GITHUB_OUTPUT
        fi

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag seqyu/yapper:${{ steps.vars.outputs.tag }}

    - name: Push the Docker image
      run: docker push seqyu/yapper:${{ steps.vars.outputs.tag }}
